### ISSUE TITLE
Add backlinks: Characters --> Situations, Works // Situations --> Works // Persons --> Works

### ISSUE THREAD

**Issue by jilltxt** [MachineVisionUiB/machinevision#24]
Now:
work --> person
work --> character
work --> situation

We need backlinks for all these. So we want to add links like this:

* [x] person --> works created
* [x] character --> works the character appears in
* [x] character --> situations the character appears in
* [x] situation --> work that the situation appears in, preferably listed WITH the work's creator and year, but if that's hard then just the title is OK

For instance, the node for Tony Stark should include links to Iron Man and other movies he is listed as a character in, and to the situations he occurs in.

<img width="932" alt="Skjermbilde 2019-07-09 kl  13 30 02" src="https://user-images.githubusercontent.com/44365847/60884881-68bee300-a24e-11e9-9fd2-be6fb809e62c.png">

**Comment by ragsol** [comment]
Also, do this for the "Character" page that links back to the "Situation" and/or "Work"?

**Comment by jilltxt** [comment]
We discussed this in our Monday morning meeting today - need this for the exhibition in February!

**Comment by steinmb** [comment]
commit MachineVisionUiB/machine-vision-theme@f7cd1d182f72fbb5cf9f8be03fcdc7b71c28df47 (HEAD -> 8.x-dev, origin/HEAD, origin/8.x-dev)
Author: Stein Magne Bjorklund <steinmb@smbjorklund.com>
Date:   Mon Feb 15 15:47:17 2021 +0100

    Issue 24 Person works created table improvements

    - Reduce block title white space. Visually easier to see that
    the header is about the data listed.
    - Increated visual weight of title, was hard to spot.
    - Force table to fill 100% of container width. Looks better in nodes.


## Before fix

![Screenshot 2021-02-15 at 15 15 06](https://user-images.githubusercontent.com/683617/107961021-a7c62600-6fa5-11eb-8aef-0130bf71477d.png)


## After fix

![Screenshot 2021-02-15 at 15 46 15](https://user-images.githubusercontent.com/683617/107961002-a0068180-6fa5-11eb-8310-7900808391db.png)

**Comment by jilltxt** [comment]
Oh, this is fabulous!! Now a character page has links to the work(s) and situations the character is in, like this! This is WONDERFUL!!!! Looks perfect!!!

<img width="796" alt="Screen Shot 2021-02-18 at 14 22 28" src="https://user-images.githubusercontent.com/44365847/108363108-dbe35600-71f4-11eb-90fd-0bd529fded94.png">

**Comment by jilltxt** [comment]
And it looks perfect for situations linking back to the work, as well! Hooray and thank you @steinmb!!

<img width="664" alt="Screen Shot 2021-02-18 at 14 26 28" src="https://user-images.githubusercontent.com/44365847/108363586-6461f680-71f5-11eb-9931-53be5905c182.png">

**Comment by jilltxt** [comment]
Reopening because I noticed that characters get backlinks to all situations in the works they are in, not just to situations that the specific character is in. Not sure if this is worth fixing? Perhaps we just change the title of the list of situations to "situations in works this character is in" or something?

<img width="833" alt="Screen Shot 2021-02-27 at 12 19 15" src="https://user-images.githubusercontent.com/44365847/109385725-4c296000-78f6-11eb-8ca9-8dd9f29a1a15.png">

**Comment by steinmb** [comment]
>Reopening because I noticed that characters get backlinks to all situations in the works they are in, not just to situations that the specific character is in. Not sure if this is worth fixing? Perhaps we just change the title of the list of situations to "situations in works this character is in" or something?

Thanks for noticing, let me have a look.

**Comment by jilltxt** [comment]
@steinmb I just noticed that the character page linking to all the situations on the work rather than just the situations that the character is in is still an issue. Maybe the best fix is to drop listing all the situations a character is in and just keep listing the Works the character appears in? We don't really need the situations.

**Comment by jilltxt** [comment]
Closing because I'm pretty sure this was resolved - it's fine the way it is!
