### ISSUE TITLE
Figure out what to do with copyright and screenshots/multimedia

### ISSUE THREAD

**Issue by ragsol** [MachineVisionUiB/machinevision#46]
Can we only use certain material (because it's public) or are there guidelines from the university? Jill has mentioned this issue before, so I'll tag her as an assignee :)

**Comment by jilltxt** [comment]
Oh, I was supposed to call a lawyer guy. I will do that.

**Comment by jilltxt** [comment]
I emailed bora@uib.no today to ask about this.

**Comment by jilltxt** [comment]
Jill will email lawyers AGAIN, and Stein Magne will hide images from people who aren't logged in.

**Comment by steinmb** [comment]
No media is now accessible to non logged in users (anonymous users), video, images, audio and documents (PDF).

**Comment by jilltxt** [comment]
The conclusion is not to make screenshots or videos visible to people who aren't logged in, and not to include them in the datasets.
