### ISSUE TITLE
Make page that lists data exports that are tagged machine vision

### ISSUE THREAD

**Issue by jilltxt** [MachineVisionUiB/machinevision#52]
We should have a way to dynamically create a page/block containing a list of all views we have creating data export.

## Problem

Tricky to know out of all the views present that machine vision use though we could create code that pick out all views creating data export though If we tag them with, example: `machinevision-export` we could use target only these.

## Suggested fix

* Tag the views with a machine vision tag (https://machine-vision.NO/admin/structure/views). I would perhaps also help the end user to pick the right one if we also make sure the views description is correct and filled out.
* Create code that create a page/block of the views.
* Decide where the list of  views should be exposed.

## How to test

* Navigate to page or page containing a block exposing these views.

**Comment by steinmb** [comment]
Updated the issue summary

**Comment by jilltxt** [comment]
Let's just tag them all machinevision?

**Comment by jilltxt** [comment]
Wasn't this done, or done enough, by putting in the ["Data exports" view](https://machine-vision.no/data_exports)?
