### ISSUE TITLE
Decide whether to have a shared way of referencing games/art/narratives in publicatiosn

### ISSUE THREAD

**Issue by jilltxt** [MachineVisionUiB/machinevision#56]

**Comment by jilltxt** [comment]
How should we reference games, artworks, novels, films, electronic literature etc in project publications? Should we agree on a shared citation style, or shall we choose our own according to discipline, publication venue and personal preferences? Should games/art/narratives be listed mixed in with scholarly sources, or should they be in a separate list, as is sometimes done in film studies? Sometimes they are simply left out of reference lists. This is a political question, in part. 

See for instance this paper, which discusses political implications:
Gualeni, Stefano, Riccardo Fassone, and Jonas Linderoth. ‘How to Reference a Digital Game’. In Proceedings of DIGRA, 17. Kyoto, Japan: Digital Games Research Association (DIGRA), 2019. http://stefano.gua-le-ni.com/papers/2019%2008%20-%20How%20to%20Reference%20a%20Digital%20Game.pdf

**Comment by ragsol** [comment]
For my MA, I put texts in one list and games in another. Everything I'm writing (and reading) atm uses one list for all, so I'm leaning towards the latter... I guess it depends on the artworks?But in an article mentioning several different genres, we could also group them as "Works referenced". I vote for referencing, though - they're as much a part of the text as other sources :)
